### ISSUE TITLE
Installer fails with "Error: Object reference not set to an instance of object."

### ISSUE THREAD

**Issue by TimLeijten** [WOA-Project/WoA-Installer-Rpi#36]
I'm trying to flash an sdcard with Windows 10 ARM for my raspberry pi. I did everything according to the tutorial, and it flashes fine but after flashing GPT image(and validating it) it just crashes with the error in the title. This is the error log of the last few lines:
```
2019-02-14 14:39:09.085 +00:00 [Verbose] Default directory for WimFolder has been set to "F:\sources"
2019-02-14 14:39:09.088 +00:00 [Verbose] Trying to load WIM metadata file at '"F:\sources\install.wim"'
2019-02-14 14:39:09.107 +00:00 [Verbose] Getting WIM stream
2019-02-14 14:39:09.108 +00:00 [Verbose] (WIM) Finding Magic Bytes...
2019-02-14 14:39:09.108 +00:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-02-14 14:39:09.108 +00:00 [Verbose] (WIM) Finding WIM XML Data...
2019-02-14 14:39:09.108 +00:00 [Verbose] (WIM) Found WIM XML Data at 032812550832
2019-02-14 14:39:09.127 +00:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "3281255083", Images: [ImageMetadata { DirectoryCount: "19154", FileCount: "86519", TotalBytes: "14402294320", HardLinkBytes: "6416458914", CreationTime: Time { HighPart: "0x01D44CED", LowPart: "0x43022989" }, LastModificationTime: Time { HighPart: "0x01D4C471", LowPart: "0x278FC22F" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: null, InstallationType: null, ServicingData: null, ProductType: null, ProductSuite: null, Languages: null, Version: Version { Major: "10", Minor: "0", Build: "17763", SpBuild: "1", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-02-14 14:39:09.132 +00:00 [Verbose] WIM metadata file at '"F:\sources\install.wim"' retrieved correctly
2019-02-14 14:39:35.563 +00:00 [Verbose] The '""' does not exist
2019-02-14 14:39:49.261 +00:00 [Verbose] Default directory for WimFolder has been set to "C:\Users\Tim\Downloads"
2019-02-14 14:39:49.264 +00:00 [Information] Importing Core Package from "C:\Users\Tim\Downloads\Core Package 1.4.0 (with USB and Ethernet).zip"
2019-02-14 14:39:49.286 +00:00 [Information] Extracting from "C:\Users\Tim\Downloads\Core Package 1.4.0 (with USB and Ethernet).zip"
2019-02-14 14:39:49.288 +00:00 [Verbose] Ensuring that '"Files"' is empty
2019-02-14 14:39:52.661 +00:00 [Information] Extraction successful from "C:\Users\Tim\Downloads\Core Package 1.4.0 (with USB and Ethernet).zip"
2019-02-14 14:39:54.577 +00:00 [Information] Core Package imported
2019-02-14 14:39:56.227 +00:00 [Verbose] The '"Files\Drivers\Pre-OOBE"' exists
2019-02-14 14:39:56.227 +00:00 [Verbose] The '"Files\Core"' exists
2019-02-14 14:39:56.227 +00:00 [Verbose] The '"Files\UEFI"' exists
2019-02-14 14:39:56.227 +00:00 [Verbose] The '"Files\Drivers"' exists
2019-02-14 14:39:56.227 +00:00 [Verbose] The '"Files\Tools"' exists
2019-02-14 14:39:56.228 +00:00 [Information] Flashing GPT image...
2019-02-14 14:39:56.232 +00:00 [Verbose] We are about to run Etcher: "Files\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE2 \"Files\Core\Gpt.zip\" --yes --no-unmount"
2019-02-14 14:39:56.234 +00:00 [Verbose] Starting process { FileName: "Files\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE2 \"Files\Core\Gpt.zip\" --yes --no-unmount" }
2019-02-14 14:39:57.245 +00:00 [Verbose] Process started sucessfully
2019-02-14 14:40:48.837 +00:00 [Information] Validating flashed image...
2019-02-14 14:41:09.223 +00:00 [Information] GPT image flashed
2019-02-14 14:41:09.227 +00:00 [Verbose] Getting "EFIESP" volume
2019-02-14 14:41:10.173 +00:00 [Verbose] Couldn't find any partition in "Number: 2, Size: 28.97 GB, AllocatedSize: 28.97 GB". Updating Storage Cache...
2019-02-14 14:41:11.292 +00:00 [Verbose] Retrying Get Partitions...
2019-02-14 14:41:11.733 +00:00 [Error] An error has ocurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Installer.Raspberry.Core.RaspberryPiDeployer.<DeployUefi>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiDeployer.<DeployCoreAndWindows>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.ViewModels.MainViewModel.<DeployUefiAndWindows>d__61.MoveNext()
2019-02-14 14:41:11.736 +00:00 [Information] Error: Object reference not set to an instance of an object.

```
I believe I did everything according to the tutorial, I downloaded the Windows 10 arm64 cmd thing, ran it, mounted the ISO, downloaded CorePackage 1.4.0 with USB and Ethernet, opened both in your tool, and pressed deploy, and it still gave me an error.

Do you know what's wrong?

Thanks!

Edit:
I also tried different SD cards. I checked what the partition table looked like when it crashed, and it appears to burn the 100mb boot image(rpi also gives me the colors when I plug the sd card in), but it doesn't seem to write the system files.

**EDIT2:**
I actually just noticed that when generating the ISO it gives an DISM error 1450. This is when making boot.wim. Does this matter?

**Comment by mattgahs** [comment]
I'm having the identical issue.

**Comment by cdw2286** [comment]
I am having the same issue

**Comment by SuperJMN** [comment]
It seems the tool isn't recovering access to the disk after it's been flashed. Sorry guys, just can tell you to try to upgrade Windows 10 to the latest version (non Insider) that is Windows 10 version 1809. It may be a problem of PowerShell.

I haven't heard of such a problem until today!

**Comment by SuperJMN** [comment]
@cdw2286 You don't have to format any partition on the card. The flash part should make they partition layout ready for the deployment.

**Comment by pgrinstead1** [comment]
Same issue for me as well. I am running the latest ver of windows 10. Any idea's?

**Comment by cdw2286** [comment]
> 
> 
> It seems the tool isn't recovering access to the disk after it's been flashed. Sorry guys, just can tell you to try to upgrade Windows 10 to the latest version (non Insider) that is Windows 10 version 1809. It may be a problem of PowerShell.
> 
> I haven't heard of such a problem until today!

Thank you for the response. I am currently upgrading Windows to build 1809 and will report back the results.

**Comment by TimLeijten** [comment]
I tried updating to 1809, and it still won't work. Always the same issue. I'll try on another PC to see if that works.

**Comment by julienrobin28** [comment]
Hi,
Had the issue when trying to do it from D:\
Also, I believe it was running as Administrator.

No problem while running from the Desktop

**Comment by cdw2286** [comment]
> 
> 
> > It seems the tool isn't recovering access to the disk after it's been flashed. Sorry guys, just can tell you to try to upgrade Windows 10 to the latest version (non Insider) that is Windows 10 version 1809. It may be a problem of PowerShell.
> > I haven't heard of such a problem until today!
> 
> Thank you for the response. I am currently upgrading Windows to build 1809 and will report back the results.

UPDATE:
After upgrading Windows to Build 1809 and following @julienrobin28 comment about running WOA Installer from the Desktop (I was previously running from the F: Drive), I was able to successfully install to my SD card.

However, when I put the SD card into the RPi and turn it on, it just goes to a Shell> prompt. Am I missing something?

**Comment by abedhaque** [comment]
@cdw2286 If it just goes to the Shell> prompt, follow the instructions here: https://discourse.pi64.win/t/frequently-asked-questions-faq/49

**Comment by pgrinstead1** [comment]
Thanks @abedhaque but it still wont boot.

**Comment by cdw2286** [comment]
> 
> 
> @cdw2286 If it just goes to the Shell> prompt, follow the instructions here: https://discourse.pi64.win/t/frequently-asked-questions-faq/49

That did the trick for me @abedhaque .  Thank you!

**Comment by DJDirtboy** [comment]
Same issue.
Run as admin from c:\winarm 
I'm on Win 10 1809

**Comment by cleveHEX** [comment]
Use https://github.com/WOA-Project/WOA-Deployer-Rpi
