### ISSUE TITLE
DISM exited with code 2

### ISSUE THREAD

**Issue by 110101011** [WOA-Project/WoA-Installer-Rpi#39]
I get "There has been a  problem during deployment: DISM exited with code 2". 

- Dism.exe /Cleanup-MountPoints <- to see if cleaning up the mountpoints fixed the issue.
- Use Diskpart to 'clean' the SDCard.
- Re-downloaded the 'WoA-Installer-Rpi'

Windows 10 build: 1809
Core-Utils: 1.4.0

Can anyone point me in the right direction?

WoA-Installer_Rpi log:

`2019-02-15 11:58:00.579 +01:00 [Verbose] Default directory for WimFolder has been set to "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi"
2019-02-15 11:58:00.616 +01:00 [Information] Importing Core Package from "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Core Package 1.4.0 (with USB and Ethernet).zip"
2019-02-15 11:58:00.657 +01:00 [Information] Extracting from "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Core Package 1.4.0 (with USB and Ethernet).zip"
2019-02-15 11:58:00.661 +01:00 [Verbose] Ensuring that '"Files"' is empty
2019-02-15 11:58:04.600 +01:00 [Verbose] Default directory for WimFolder has been set to "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi"
2019-02-15 11:58:04.609 +01:00 [Verbose] Trying to load WIM metadata file at '"C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim"'
2019-02-15 11:58:04.675 +01:00 [Verbose] Getting WIM stream
2019-02-15 11:58:04.678 +01:00 [Verbose] (WIM) Finding Magic Bytes...
2019-02-15 11:58:04.679 +01:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-02-15 11:58:04.679 +01:00 [Verbose] (WIM) Finding WIM XML Data...
2019-02-15 11:58:04.679 +01:00 [Verbose] (WIM) Found WIM XML Data at 043431349642
2019-02-15 11:58:04.763 +01:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4343134964", Images: [ImageMetadata { DirectoryCount: "22565", FileCount: "98622", TotalBytes: "17051468701", HardLinkBytes: "6590715483", CreationTime: Time { HighPart: "0x01D44CED", LowPart: "0x43022989" }, LastModificationTime: Time { HighPart: "0x01D4C3E0", LowPart: "0xE4EADD89" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17763.1;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17763", SpBuild: "292", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-02-15 11:58:04.772 +01:00 [Verbose] WIM metadata file at '"C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim"' retrieved correctly
2019-02-15 11:58:04.776 +01:00 [Information] Extraction successful from "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Core Package 1.4.0 (with USB and Ethernet).zip"
2019-02-15 11:58:06.850 +01:00 [Information] Core Package imported
2019-02-15 11:58:08.913 +01:00 [Information] Flashing GPT image...
2019-02-15 11:58:08.920 +01:00 [Verbose] We are about to run Etcher: "Files\Tools\Etcher-Cli\x86\Etcher" "-d \\.\PHYSICALDRIVE1 \"Files\Core\Gpt.zip\" --yes --no-unmount"
2019-02-15 11:58:08.924 +01:00 [Verbose] Starting process { FileName: "Files\Tools\Etcher-Cli\x86\Etcher", Arguments: "-d \\.\PHYSICALDRIVE1 \"Files\Core\Gpt.zip\" --yes --no-unmount" }
2019-02-15 11:58:09.224 +01:00 [Verbose] Process started sucessfully
2019-02-15 11:59:12.783 +01:00 [Information] Validating flashed image...
2019-02-15 11:59:53.873 +01:00 [Information] GPT image flashed
2019-02-15 11:59:53.881 +01:00 [Verbose] Getting "EFIESP" volume
2019-02-15 11:59:54.346 +01:00 [Verbose] Couldn't find any partition in "Number: 1, Size: 28.97 GB, AllocatedSize: 28.97 GB". Updating Storage Cache...
2019-02-15 11:59:54.785 +01:00 [Verbose] Retrying Get Partitions...
2019-02-15 11:59:58.383 +01:00 [Verbose] Copying directory "Files\UEFI" to "."
2019-02-15 11:59:58.386 +01:00 [Verbose] Copying file "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Files\UEFI\bootcode.bin" to "E:\bootcode.bin"
2019-02-15 12:00:01.405 +01:00 [Verbose] Copying file "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Files\UEFI\config.txt" to "E:\config.txt"
2019-02-15 12:00:01.549 +01:00 [Verbose] Copying file "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Files\UEFI\fixup.dat" to "E:\fixup.dat"
2019-02-15 12:00:01.614 +01:00 [Verbose] Copying file "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Files\UEFI\readme.md" to "E:\readme.md"
2019-02-15 12:00:01.653 +01:00 [Verbose] Copying file "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Files\UEFI\RPI_EFI.fd" to "E:\RPI_EFI.fd"
2019-02-15 12:01:18.298 +01:00 [Verbose] Copying file "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\Files\UEFI\start.elf" to "E:\start.elf"
2019-02-15 12:01:24.129 +01:00 [Information] Deploying Windows 10 ARM64...
2019-02-15 12:01:24.129 +01:00 [Information] Cleaning existing Windows 10 ARM64 partitions...
2019-02-15 12:01:24.137 +01:00 [Information] Creating Windows partition...
2019-02-15 12:01:25.673 +01:00 [Verbose] Mounting volume "Label: , Size: 0 b, Partition: Disk: Number: 1, Size: 28.97 GB, AllocatedSize: 28.97 GB, Number: 3, Letter: "
2019-02-15 12:01:38.000 +01:00 [Information] Windows Partition created successfully
2019-02-15 12:01:38.003 +01:00 [Verbose] Getting "WindowsARM" volume
2019-02-15 12:01:39.148 +01:00 [Information] Applying Windows Image...
2019-02-15 12:01:39.154 +01:00 [Verbose] Checking image at "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim", with index "C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim"
2019-02-15 12:01:39.154 +01:00 [Verbose] Image file at '"C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim"' exists
2019-02-15 12:01:39.154 +01:00 [Verbose] Getting WIM stream
2019-02-15 12:01:39.154 +01:00 [Verbose] (WIM) Finding Magic Bytes...
2019-02-15 12:01:39.154 +01:00 [Verbose] (WIM) Found Magic Bytes at 0
2019-02-15 12:01:39.154 +01:00 [Verbose] (WIM) Finding WIM XML Data...
2019-02-15 12:01:39.154 +01:00 [Verbose] (WIM) Found WIM XML Data at 043431349642
2019-02-15 12:01:39.174 +01:00 [Verbose] Wim metadata deserialized correctly WimMetadata { TotalBytes: "4343134964", Images: [ImageMetadata { DirectoryCount: "22565", FileCount: "98622", TotalBytes: "17051468701", HardLinkBytes: "6590715483", CreationTime: Time { HighPart: "0x01D44CED", LowPart: "0x43022989" }, LastModificationTime: Time { HighPart: "0x01D4C3E0", LowPart: "0xE4EADD89" }, WimBoot: "0", Windows: Windows { Arch: "12", ProductName: "Microsoft® Windows® Operating System", EditionId: "Professional", InstallationType: "Client", ServicingData: ServicingData { GdrDuRevision: "0", PKeyConfigVersion: "10.0.17763.1;2016-01-01T00:00:00Z" }, ProductType: "WinNT", ProductSuite: "Terminal Server", Languages: Languages { Language: "en-US", Default: "en-US" }, Version: Version { Major: "10", Minor: "0", Build: "17763", SpBuild: "292", SpLevel: "0" }, SystemRoot: "WINDOWS" }, Name: "Windows 10 Pro", Description: "Windows 10 Pro", Flags: null, DiplayName: "Windows 10 Pro", DisplayDescription: "Windows 10 Pro", Index: "1" }] }
2019-02-15 12:01:39.174 +01:00 [Verbose] We are about to run DISM: "C:\Windows\SysNative\dism.exe" "/Apply-Image /ImageFile:\"C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim\" /Index:1 /ApplyDir:F:\"
2019-02-15 12:01:39.175 +01:00 [Verbose] Starting process { FileName: "C:\Windows\SysNative\dism.exe", Arguments: "/Apply-Image /ImageFile:\"C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim\" /Index:1 /ApplyDir:F:\" }
2019-02-15 12:01:39.186 +01:00 [Verbose] Process started sucessfully
2019-02-15 12:09:03.460 +01:00 [Error] An error has ocurred
Installer.Core.Exceptions.DeploymentException: There has been a problem during deployment: DISM exited with code 2.
   at Installer.Core.FullFx.DismImageService.<ApplyImage>d__1.MoveNext() in C:\Users\super\source\repos\Install\Installer.Core.FullFx\DismImageService.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiWindowsDeployer.<ApplyWindowsImage>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiWindowsDeployer.<Deploy>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiDeployer.<DeployWindows>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.Core.RaspberryPiDeployer.<DeployCoreAndWindows>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Installer.Raspberry.ViewModels.MainViewModel.<DeployUefiAndWindows>d__59.MoveNext()
2019-02-15 12:09:03.478 +01:00 [Information] Error: There has been a problem during deployment: DISM exited with code 2.
`

Dism log:

`2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Dism.exe version: 10.0.17763.1
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Executing command line: "C:\Windows\SysNative\dism.exe" /Apply-Image /ImageFile:"C:\Users\justi\Desktop\Win10Arm\WoA.Installer.for.Raspberry.Pi\install.wim" /Index:1 /ApplyDir:F:\
2019-02-15 12:01:39, Info                  DISM   DISM Provider Store: PID=4928 TID=2496 Getting the collection of providers from a local provider store type. - CDISMProviderStore::GetProviderCollection
2019-02-15 12:01:39, Info                  DISM   DISM Provider Store: PID=4928 TID=2496 Connecting to the provider located at C:\Windows\system32\Dism\FolderProvider.dll. - CDISMProviderStore::Internal_LoadProvider
2019-02-15 12:01:39, Warning               DISM   DISM Provider Store: PID=4928 TID=2496 Failed to load the provider: C:\Windows\system32\Dism\SiloedPackageProvider.dll. - CDISMProviderStore::Internal_GetProvider(hr:0x8007007e)
2019-02-15 12:01:39, Info                  DISM   DISM Provider Store: PID=4928 TID=2496 Connecting to the provider located at C:\Windows\system32\Dism\FfuProvider.dll. - CDISMProviderStore::Internal_LoadProvider
2019-02-15 12:01:39, Info                  DISM   DISM Provider Store: PID=4928 TID=2496 Connecting to the provider located at C:\Windows\system32\Dism\WimProvider.dll. - CDISMProviderStore::Internal_LoadProvider
2019-02-15 12:01:39, Info                  DISM   DISM Provider Store: PID=4928 TID=2496 Connecting to the provider located at C:\Windows\system32\Dism\VHDProvider.dll. - CDISMProviderStore::Internal_LoadProvider
2019-02-15 12:01:39, Info                  DISM   DISM Provider Store: PID=4928 TID=2496 Connecting to the provider located at C:\Windows\system32\Dism\ImagingProvider.dll. - CDISMProviderStore::Internal_LoadProvider
2019-02-15 12:01:39, Info                  DISM   DISM Provider Store: PID=4928 TID=2496 Connecting to the provider located at C:\Windows\system32\Dism\CompatProvider.dll. - CDISMProviderStore::Internal_LoadProvider
2019-02-15 12:01:39, Warning               DISM   DISM Provider Store: PID=4928 TID=2496 Failed to load the provider: C:\Windows\system32\Dism\MetaDeployProvider.dll. - CDISMProviderStore::Internal_GetProvider(hr:0x8007007e)
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Got the collection of providers. Now enumerating them to build the command table.
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Attempting to add the commands from provider: DISM Log Provider
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Attempting to add the commands from provider: FolderManager
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Attempting to add the commands from provider: FfuManager
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Succesfully registered commands for the provider: FfuManager.
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Attempting to add the commands from provider: WimManager
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Succesfully registered commands for the provider: WimManager.
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Attempting to add the commands from provider: VHDManager
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Attempting to add the commands from provider: GenericImagingManager
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Succesfully registered commands for the provider: GenericImagingManager.
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Attempting to add the commands from provider: Compatibility Manager
2019-02-15 12:01:39, Info                  DISM   DISM.EXE: Succesfully registered commands for the provider: Compatibility Manager.
[4928] [0x80070002] RestoreDirMetadata:(2544): The system cannot find the file specified.
[4928] [0x8144012d] 
2019-02-15 12:09:03, Warning               DISM   DISM WIM Provider: PID=4928 [RestoreDirMetadata:(2550) -> Error restoring directory metadata] F:\Windows\WinSxS\arm64_microsoft-windows-p..ctivescan.resources_31bf3856ad364e35_10.0.17763.1_en-us_06992b36f3e2b22f (HRESULT=0x80070002) - CWimManager::WimProviderMsgLogCallback
[4928] [0x80070002] RestoreDirMetadata:(2710): The system cannot find the file specified.
[4928] [0x80070002] WimCreateDirectory:(3272): The system cannot find the file specified.
[4928] [0xc144012e] 
2019-02-15 12:09:03, Error                 DISM   DISM WIM Provider: PID=4928 F:\Windows\WinSxS\arm64_microsoft-windows-p..ctivescan.resources_31bf3856ad364e35_10.0.17763.1_en-us_06992b36f3e2b22f (HRESULT=0x80070002) - CWimManager::WimProviderMsgLogCallback
[4928] [0x80070002] RestoreDirTree:(3523): The system cannot find the file specified.
[4928] [0x80070002] WIMApplyImageInternal:(709): The system cannot find the file specified.
2019-02-15 12:09:03, Error                 DISM   DISM WIM Provider: PID=4928 TID=2496 onecore\base\ntsetup\opktools\dism\providers\wimprovider\dll\wimmanager.cpp:1036 - CWimManager::Apply(hr:0x80070002)
2019-02-15 12:09:03, Error                 DISM   DISM Imaging Provider: PID=4928 TID=2496 onecore\base\ntsetup\opktools\dism\providers\imagingprovider\dll\genericimagingmanager.cpp:2813 - CGenericImagingManager::InternalCmdWimApply(hr:0x80070002)
2019-02-15 12:09:03, Error                 DISM   DISM Imaging Provider: PID=4928 TID=2496 onecore\base\ntsetup\opktools\dism\providers\imagingprovider\dll\genericimagingmanager.cpp:547 - CGenericImagingManager::ExecuteCmdLine(hr:0x80070002)
2019-02-15 12:09:03, Info                  DISM   DISM.EXE: Image session has been closed. Reboot required=no.`

**Comment by SuperJMN** [comment]
It looks like a corrupted .wim. Can you please download it again? 
BTW, use Windows 10 build 17134. It's a known working build 😉

**Comment by 110101011** [comment]
Will download 17134 and try that version. ;)

I've extracted the install.vim a couple of time from my created ISO, so the ISO must be corrupt.

**Comment by 110101011** [comment]
Turns out DISM my card reader and my 32Gb SdCard don't go along 😑

So I'm gonna use WoA-installer to write to an usb-stick and DD the contents to my SDCard should work too.

So this issue can be closed 👍
